identidock:
  build: .
  ports:
   - "5000:5000"
   - "3000:3000"
  environment:
    ENV: DEV 
  volumes:
    - ./app:/app
  links:
    - dnmonster
    - redis
    - grafana
    - influxdb
    - telegraf

dnmonster:
  image: amouat/dnmonster:1.0

redis:
  image: redis:3.0

grafana:
  container_name: grafana
  image: grafana/grafana:7.2.1-ubuntu
  ports: 
    - "3000:3000" 
  links: 
    - influxdb

influxdb:
  container_name: influxdb
  image: influxdb:1.0.2
  ports: 
    - "8083:8083"
    - "8086:8086"
  volumes: 
    ./influxdb:/var/lib/influxdb
  restart: always

telegraf:
  container_name: telegraf
  image: telegraf:1.3.3
