version: "3.8"

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        expose: 
            - 3000
        depends_on:
            - mongodb
        deploy:
            replicas: 3

    mongodb:
        container_name: mongodb
        image: mongo:latest
        hostname: mongodb
        ports:
            - "27017:27017"
        # volumes:
        #    - /usr/local/var/mongodb:/data

    nginx:
        image: nginx:latest
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf:ro
        depends_on:
            - app
        ports:
            - "4000:4000"
        